version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puppeteer-scraping-api
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - PORT=8001
      - API_TOKEN=${API_TOKEN:-123}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 2G

networks:
  app-network:
    driver: bridge 