version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puppeteer-scraping-api
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - PORT=8001
      - API_TOKEN=${API_TOKEN:-123}  # Usa variável de ambiente ou '123' como fallback
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puppeteer-scraping-api-test
    environment:
      - NODE_ENV=test
      - PORT=8001
      - API_TOKEN=${API_TOKEN:-123}
      - API_URL=http://api:8001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      api:
        condition: service_healthy
    command: node test-api.js 